# Generated by Django 2.2.19 on 2021-03-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='nome_do_arquivo',
            field=models.CharField(max_length=100, verbose_name='Nome do arquivo'),
        ),
    ]
