# Generated by Django 2.2.19 on 2021-04-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0002_auto_20210412_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='periodo',
            field=models.CharField(choices=[('1º', '1º'), ('2º', '2º'), ('3º', '3º'), ('4º', '4º'), ('5º', '5º'), ('6º', '6º'), ('7º', '7º'), ('8º', '8º'), ('9º', '9º'), ('10º', '10º')], default='', max_length=3, verbose_name='Período'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turma',
            name='horario_de_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de início'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='horario_de_termino',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de término'),
        ),
    ]
