# Generated by Django 2.2.19 on 2021-04-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0004_auto_20210412_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='arquivo',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='arquivo',
            field=models.ManyToManyField(blank=True, null=True, to='aplic.Arquivo'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='dia_da_semana',
            field=models.CharField(choices=[('1', 'Domingo'), ('2', 'Segunda-feira'), ('3', 'Terça-feira'), ('4', 'Quarta-feira'), ('5', 'Quinta-feira'), ('6', 'Sexta-feira'), ('7', 'Sábado')], max_length=13, verbose_name='Dia da Semana'),
        ),
    ]
