# Generated by Django 2.2.19 on 2021-04-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0005_auto_20210412_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='arquivo',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='arquivo',
            field=models.FileField(default='', upload_to='', verbose_name='Arquivo'),
            preserve_default=False,
        ),
    ]
