# Generated by Django 2.2.19 on 2021-04-13 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0007_auto_20210413_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='professor',
        ),
    ]
