# Generated by Django 2.2.19 on 2021-04-13 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0008_remove_turma_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.Professor'),
        ),
        migrations.RemoveField(
            model_name='turma',
            name='disciplina',
        ),
        migrations.AddField(
            model_name='turma',
            name='disciplina',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='aplic.Disciplina'),
            preserve_default=False,
        ),
    ]
