# Generated by Django 2.2.19 on 2021-04-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0009_auto_20210413_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='horario_de_inicio',
            field=models.TimeField(verbose_name='Horário de início'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='horario_de_termino',
            field=models.TimeField(verbose_name='Horário de término'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='periodo',
            field=models.CharField(choices=[('1', '1º'), ('2', '2º'), ('3', '3º'), ('4', '4º'), ('5', '5º'), ('6', '6º'), ('7', '7º'), ('8', '8º'), ('9', '9º'), ('10', '10º'), ('11', '11º'), ('12', '12º')], max_length=3, verbose_name='Período'),
        ),
    ]
