# Generated by Django 2.2.19 on 2021-04-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0011_auto_20210413_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='dia_da_semana',
            field=models.CharField(choices=[('1', 'Domingo'), ('2', 'Segunda-feira'), ('3', 'Terça-feira'), ('4', 'Quarta-feira'), ('5', 'Quinta-feira'), ('6', 'Sexta-feira'), ('7', 'Sábado')], max_length=13, verbose_name='Dia da Semana'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='periodo',
            field=models.CharField(choices=[('1', '1º'), ('2', '2º'), ('3', '3º'), ('4', '4º'), ('5', '5º'), ('6', '6º'), ('7', '7º'), ('8', '8º'), ('9', '9º'), ('10', '10º'), ('11', '11º'), ('12', '12º')], max_length=3, verbose_name='Período'),
        ),
    ]
