# Generated by Django 2.2.19 on 2021-04-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0013_disciplina_credito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='E-mail'),
        ),
    ]
