# Generated by Django 2.2.19 on 2021-04-13 21:50

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0014_auto_20210413_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='senha',
            field=django_cryptography.fields.encrypt(models.CharField(default=123, max_length=50)),
            preserve_default=False,
        ),
    ]
