# Generated by Django 2.2.19 on 2021-04-13 22:06

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0015_aluno_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='email',
            field=models.EmailField(default='', max_length=200, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='senha',
            field=django_cryptography.fields.encrypt(models.CharField(default='', max_length=50)),
            preserve_default=False,
        ),
    ]
