# Generated by Django 2.2.19 on 2021-04-13 22:23

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0017_auto_20210413_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='media/profiles/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='media/profiles/%Y/%m/%d'),
        ),
    ]
