# Generated by Django 2.2.19 on 2021-04-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0020_auto_20210413_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='composicao',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], default='P1', max_length=3, verbose_name='Composição'),
            preserve_default=False,
        ),
    ]
